global using AutoFixture.Xunit2;
global using AutoMapper;
global using FluentAssertions;
global using Moq;
global using ServicesAPI.Domain;
global using ServicesAPI.Persistence;
global using ServicesAPI.Persistence.Repositories;
global using ServicesAPI.Tests.Attributes;
global using Xunit;
